  - name: Устанавливаем rsyslog
    ansible.builtin.apt:
      name: rsyslog
      state: present

  - name: Копируем rsyslog_all.conf
    ansible.builtin.template:
      src: rsyslog_all.conf
      dest: /etc/rsyslog.d/all.conf

  - name: Перезапускаем сервис rsyslog
    ansible.builtin.service:
      name: rsyslog
      state: restarted