- name: set up vlan1
  hosts: testClient1,testServer1
  become: yes
  tasks:
    #Добавление темплейта в файл /etc/sysconfig/network-scripts/ifcfg-vlan1
    - name: set up vlan1
      template:
        src: ifcfg-vlan1.j2
        dest: /etc/sysconfig/network-scripts/ifcfg-vlan1
        owner: root
        group: root
        mode: 0644
    
    #Перезапуск службы NetworkManager
    - name: restart network for vlan1
      service:
        name: NetworkManager
        state: restarted

- name: set up vlan2
  hosts: testClient2,testServer2 
  become: yes
  tasks:
    #Добавление темплейта в файл /etc/netplan/50-cloud-init.yaml
    - name: set up vlan2
      template:
        src: 50-cloud-init.yaml.j2
        dest: /etc/netplan/50-cloud-init.yaml 
        owner: root
        group: root
        mode: 0644

    - name: apply set up vlan2
      shell: netplan apply
      become: true

- name: set up bond0
  hosts: inetRouter,centralRouter
  become: yes
  tasks:
  - name: set up ifcfg-bond0
    template:
      src: ifcfg-bond0.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-bond0
      owner: root
      group: root
      mode: 0644
  
  - name: set up eth1,eth2
    copy: 
      src: "{{ item }}" 
      dest: /etc/sysconfig/network-scripts/
      owner: root
      group: root
      mode: 0644
    with_items:
      - templates/ifcfg-eth1
      - templates/ifcfg-eth2

  - name: restart hosts for bond0
    reboot:
      reboot_timeout: 3600
