# -*- mode: ruby -*- 
# vi: set ft=ruby : vsa
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "2004.01"  
  config.vm.provider "virtualbox" do |v|
     v.memory = 1024
     v.cpus = 1
  end

  boxes = [
    { :name => "log-server",
      :ip => "192.168.56.15",
      :ansible => "ansible_log_server.yml"
    },
    { :name => "web",
      :ip => "192.168.56.10",
      :ansible => "ansible_web.yml"
    },
    { :name => "log-all",
      :ip => "192.168.56.11",
      :ansible => "ansible_log_all.yml"
    }
  ]

  boxes.each do |opts|  
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network "private_network", ip: opts[:ip]
      
      config.vm.provision "ansible" do |ansible|
        ansible.playbook = opts[:ansible]
        ansible.verbose = "v"
      end
    end
  end
end